name: Test

on: [push, pull_request]

jobs:
  test_ubun_ruby_2_5:
    name: Ubuntu Ruby 2.5
    runs-on: ubuntu-latest
    env:
      GEMFILE_DIR: ruby-2.5
      RUBY_VERSION: 2.5.x

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        version: $RUBY_VERSION
    - name: Setup bundler
      uses: ./.github/actions/setup-bundler-for-testing
    - name: Build
      run: |
        bundle install
        ./$GEMFILE_DIR/bin/rake


  test_ubun_ruby_2_6:
    name: Ubuntu Ruby 2.6
    runs-on: ubuntu-latest
    env:
      GEMFILE_DIR: ruby-2.6
      RUBY_VERSION: 2.6.x

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        version: $RUBY_VERSION
    - name: Setup bundler
      uses: ./.github/actions/setup-bundler-for-testing
    - name: Build
      run: |
        bundle install
        ./$GEMFILE_DIR/bin/rake


  test_ubun_ruby_2_7:
    name: Ubuntu Ruby 2.7
    runs-on: ubuntu-latest
    env:
      GEMFILE_DIR: .
      RUBY_VERSION: 2.7.x

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        version: $RUBY_VERSION
    - name: Setup bundler
      uses: ./.github/actions/setup-bundler-for-testing
    - name: Build
      run: |
        bundle install
        ./$GEMFILE_DIR/bin/rake

